package com.mars.model;
// Generated 2017/9/30 �U�� 03:28:16 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductDetail generated by hbm2java
 */
@Entity
@Table(name = "PRODUCT_DETAIL", schema = "MARS")
public class ProductDetail implements java.io.Serializable {

	private String uuid;
	private String name;
	private BigDecimal prize;
	private Date date;

	public ProductDetail() {
	}

	public ProductDetail(String uuid, String name, BigDecimal prize, Date date) {
		this.uuid = uuid;
		this.name = name;
		this.prize = prize;
		this.date = date;
	}

	@Id

	@Column(name = "UUID", unique = true, nullable = false, length = 36)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "NAME", nullable = false, length = 36)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PRIZE", nullable = false, precision = 23, scale = 0)
	public BigDecimal getPrize() {
		return this.prize;
	}

	public void setPrize(BigDecimal prize) {
		this.prize = prize;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE", nullable = false, length = 7)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
